# Generated by Django 4.2.1 on 2023-05-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_rename_prodotto_product_rename_utente_user_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isAmm',
            field=models.BooleanField(null=True),
        ),
    ]
